from . import zones
from . import product_template
from . import tariff_block
from . import tariff_range
from . import meter_serial
from . import meter_group
from . import meter_discount
from . import billing_meter
from . import crm_lead_inherit
from . import res_partner_inherit
from . import meter_reading
from . import account_move_inherit
